apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps 
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/Saikiran121/gitops-argocd-project.git
    targetRevision: HEAD 
    path: ./declarative/app-of-apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 